### ISSUE TITLE
Use hardhat-deploy for contract deployments

### ISSUE THREAD

**Issue by sebastianst** [yieldgate/yieldgate#37]
We currently use a self-made script for contract deployment and saving of deployed addresses to files for the frontend. We now found the feature rich hardhat plugin https://github.com/wighawag/hardhat-deploy which does this, including etherscan contract validation. So we should switch to using it.

**Comment by wottpal** [comment]
I spend the last hours switching my boilerplate to use `hardhat-deploy` and did some other integration improvements down the road. Just for reference, those are the things I would do to make this work for yg:

### hardhat:

- [ ] remove the `scripts/deploy.ts` script and replace it with a new `deploy/001_deploy_yieldgate.ts` script that uses hardhat-deploy (example: https://github.com/ethathon/ethathon/blob/main/packages/hardhat/deploy/001_deploy_lock.ts)
- [ ] delete https://github.com/yieldgate/yieldgate/blob/develop/packages/hardhat/shared/saveFrontendAddressFiles.ts
- [ ] update prettierignore/eslintignore/gitignore accordingly
- [ ] move artifacts back from frontend to hardhat again
- [ ] mimc hardhat-deploy deployments-files for existing mumbai / poss. rinkeby deployments

### frontend

- [ ]  replace `lib/useYieldgateContracts.ts` with a new `useDeployments.ts` hook that works with the new hardhat-deploy export format (example https://github.com/ethathon/ethathon/blob/main/packages/frontend/src/shared/useDeployments.ts)
- [ ] remove `addresses` & `artifacts`
- [ ] add new `deployments/deployments.ts` that dynamically aggregates all deployment json-files (example https://github.com/ethathon/ethathon/blob/main/packages/frontend/src/deployments/deployments.ts)
- [ ] add types for hardhat exports (example https://github.com/ethathon/ethathon/blob/main/packages/frontend/src/types/hardhat.d.ts)
- [ ] rewrite all frontend contract interactions (i.e. on profile-page, or profiles-list) to comply with the new hook and abi- and address-locations
- [ ] update wagmi (no breaking changes for us)

### project-level:

- [ ] as abis & addresses are in one file from now on, we need to do an actual deployment (at least once) to create the files needed for building the frontend locally. – at least if we want to keep 1337/hardhat to be a supported chain. if not, and we only use mumbai & rinkeby/goerli (even locally) we wouldn't need that. but if we want to, i need to include the hardhat node-start as well as the deployment within the `turbo run dev` command. at least, this fortunately is only one command with hardhat-deploy. (already did it here: https://github.com/ethathon/ethathon/blob/a066797393a4c7766ce5808d326471d1528de0bf/turbo.json#L23)

### beyond scope:

In the boilerplate i renamed all rpc-url environment variables to reflect the actual chain-id instead of an arbitrary identifier (see https://github.com/ethathon/ethathon/blob/a066797393a4c7766ce5808d326471d1528de0bf/packages/frontend/src/shared/environment.ts#L13). this way i can dynamically assign all rpc-urls in the `wagmiClient` (see https://github.com/ethathon/ethathon/blob/a066797393a4c7766ce5808d326471d1528de0bf/packages/frontend/src/shared/wagmiClient.ts#L22). imo this has two advantages: (1) rpcs can be assigned automatically and therefore when adding a chain there is no need for manual edits in this file, and (2) it immediately throws errors on start if i say i support a chain in my environment but don't add the respective rpcs. 

But I think the latter would be too much in conflict with what @raulrpearson is doing in #35 and therefore I would leave that for later and/or discussion.

**Comment by sebastianst** [comment]
And please also add etherscan contract validation ❤️

**Comment by wottpal** [comment]
>  mimc hardhat-deploy deployments-files for existing mumbai / poss. rinkeby deployments

I'll probably skip this one as we re-deploy soon anyways because of contract changes. Seems a little bit tedious to create this metadata by hand for previous deployments. Ok with that, @sebastianst?

**Comment by sebastianst** [comment]
Yes sounds reasonable!
