### ISSUE TITLE
Confirm Prettier + CI + VS Code setup

### ISSUE THREAD

**Issue by raulrpearson** [yieldgate/yieldgate#39]
I've run into a CI lint error with #35. It seems that prettier format write on save hadn't run on the file locally because of this [prettier ignore line](https://github.com/yieldgate/yieldgate/blob/c78e32f6f0435024d4620d3146a093f2f8f95fc8/.prettierignore#L3). More insight in [this comment](https://github.com/prettier/prettier/issues/4081#issuecomment-1030939679).

Still investigating, let me know what you guys think.

**Comment by wottpal** [comment]
currently investigating. annoying issue. may i be right that this only concerns lint-staged and not the new pnpm run lint:all command? because we only have one lint-staged in the root and therefore prettier only runs from the root in this case?

fyi you can attach —loglevel debug to prettier commands and —verbose to the lint-staged command to see which files are taken into account. but you don’t have to, i’m already digging deeper right now 🙂

**Comment by wottpal** [comment]
After some more investigation, I think my initial assumption was correct. Please double-check, @raulrpearson. 

One more tip for debugging is to use another code editor or temporarily deactivate the code-actions-on-save in VSCode. Also, don't forget to actually stage the files that they are taken into account by lint-staged.
